# Generated by Django 2.0 on 2017-12-11 14:39

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marker', '0002_markedtext_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markedtext',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
