# Generated by Django 2.0 on 2018-02-05 12:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marker', '0003_auto_20171211_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='markedtext',
            name='analysis',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
