# Generated by Django 2.0 on 2018-02-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marker', '0005_auto_20180205_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='markedtext',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
