# Generated by Django 2.0 on 2018-02-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marker', '0006_markedtext_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='markedtext',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='markedtext',
            name='title',
            field=models.TextField(blank=True, default='Manjka naslov', null=True),
        ),
    ]
