# Generated by Django 2.0 on 2018-08-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marker', '0009_markedtext_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='markedtext',
            name='og_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='markedtext',
            name='og_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
